version: '3.3'
services:
  aeropuerto:
    image: amazoncorretto:19
    volumes:
    - ./app:/app
    ports:
    - 8080:8080
    environment:
     MYSQL_HOST: mysql
    command:
    - java
    - -jar
    - /app/Aeropuerto.jar
    depends_on:
    - mysql
    links:
    - mysql
    restart: always
   
  empleados:
    image: amazoncorretto:19
    volumes:
    - ./app:/app
    ports:
    - 8083:8080
    environment:
     MYSQL_HOST: mysql2
    command:
    - java
    - -jar
    - /app/Empleados.jar
    depends_on:
    - mysql2
    links:
    - mysql2
    restart: always


  mysql2:
    image: mysql
    ports:
      - "3308:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=yo
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=Aeropuerto
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"


  mysql:
    image: mysql2
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=yo
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=Empleados
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
